# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FluxOperator < Formula
  desc "Flux Operator CLI"
  homepage "https://fluxcd.control-plane.io/operator/cli"
  version "0.24.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/controlplaneio-fluxcd/flux-operator/releases/download/v0.24.1/flux-operator_0.24.1_darwin_amd64.tar.gz"
      sha256 "60833b5953dcdcb256c5529d1bb0fed51cb835c01dbd617596986d9d0e19d1ef"

      def install
        bin.install "flux-operator"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/controlplaneio-fluxcd/flux-operator/releases/download/v0.24.1/flux-operator_0.24.1_darwin_arm64.tar.gz"
      sha256 "86e62ff9cbf508d8f8e9a5d1632021022f2d4f0e08caf415a2922f785203b19b"

      def install
        bin.install "flux-operator"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/controlplaneio-fluxcd/flux-operator/releases/download/v0.24.1/flux-operator_0.24.1_linux_amd64.tar.gz"
        sha256 "409f647cb6d74e34b1dca6035b8dbe4ce6487262de39be95261668aebc2ab1cd"

        def install
          bin.install "flux-operator"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/controlplaneio-fluxcd/flux-operator/releases/download/v0.24.1/flux-operator_0.24.1_linux_arm64.tar.gz"
        sha256 "632265fb41c921d1caf85857ed6116917d4566afeab6a0863d2be0073d82eedc"

        def install
          bin.install "flux-operator"
        end
      end
    end
  end

  test do
    system "#{bin}/flux-operator--version"
  end
end
