# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FluxOperator < Formula
  desc "Flux Operator CLI"
  homepage "https://fluxcd.control-plane.io/operator/cli"
  version "0.57.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/controlplaneio-fluxcd/flux-operator/releases/download/v0.57.0/flux-operator_0.57.0_darwin_amd64.tar.gz"
      sha256 "dea268f9ae341c81e77bd5dda25f0c94a543c6acf629cd79e2de30f9e999a94b"

      def install
        bin.install "flux-operator"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/controlplaneio-fluxcd/flux-operator/releases/download/v0.57.0/flux-operator_0.57.0_darwin_arm64.tar.gz"
      sha256 "4dc9b3026f3b2d9fc7f13d9f6f5805036cff7d0af94d684abc928431c914138a"

      def install
        bin.install "flux-operator"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/controlplaneio-fluxcd/flux-operator/releases/download/v0.57.0/flux-operator_0.57.0_linux_amd64.tar.gz"
        sha256 "abd705d2772912c482379103163df9537b4828326d29be114ec1da1cbf7a81b3"

        def install
          bin.install "flux-operator"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/controlplaneio-fluxcd/flux-operator/releases/download/v0.57.0/flux-operator_0.57.0_linux_arm64.tar.gz"
        sha256 "ac2ac47b55dc42459ab8de71ddb1e8687597e80320dbba43ace5d9904f219d1d"

        def install
          bin.install "flux-operator"
        end
      end
    end
  end

  test do
    system "#{bin}/flux-operator--version"
  end
end
