# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FluxOperatorMcp < Formula
  desc "Flux MCP Server"
  homepage "https://fluxcd.control-plane.io/mcp/"
  version "0.44.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/controlplaneio-fluxcd/flux-operator/releases/download/v0.44.0/flux-operator-mcp_0.44.0_darwin_amd64.tar.gz"
      sha256 "4ed2060559c34012a747a32c08360aeaa2b4d797ef4c574474000b1875723d3a"

      def install
        bin.install "flux-operator-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/controlplaneio-fluxcd/flux-operator/releases/download/v0.44.0/flux-operator-mcp_0.44.0_darwin_arm64.tar.gz"
      sha256 "f5e0e99fa56ec4f934d69afa23a1dbf59de10c61ac7527d97365eab454eb0841"

      def install
        bin.install "flux-operator-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/controlplaneio-fluxcd/flux-operator/releases/download/v0.44.0/flux-operator-mcp_0.44.0_linux_amd64.tar.gz"
        sha256 "fa6d69edcbc7decaeafd2c29cffc4df22891938f9e528e796c03a60615f314b0"

        def install
          bin.install "flux-operator-mcp"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/controlplaneio-fluxcd/flux-operator/releases/download/v0.44.0/flux-operator-mcp_0.44.0_linux_arm64.tar.gz"
        sha256 "ecfa08704beb1cbe53e841ee90e1ff3a594be5a3c14bf7bfcd0eecbfa81b8ac4"

        def install
          bin.install "flux-operator-mcp"
        end
      end
    end
  end

  test do
    system "#{bin}/flux-operator-mcp --version"
  end
end
