# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FluxOperator < Formula
  desc "Flux Operator CLI"
  homepage "https://fluxcd.control-plane.io/operator/cli"
  version "0.28.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/controlplaneio-fluxcd/flux-operator/releases/download/v0.28.0/flux-operator_0.28.0_darwin_amd64.tar.gz"
      sha256 "1d00ff61c745c759fdf06deac905dbf18564806a41c07484c7c5051d2fd071c6"

      def install
        bin.install "flux-operator"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/controlplaneio-fluxcd/flux-operator/releases/download/v0.28.0/flux-operator_0.28.0_darwin_arm64.tar.gz"
      sha256 "baa4f6479c62251debc9724a131a06bf4c31b6c0437a5fee843cf0a71913f3c0"

      def install
        bin.install "flux-operator"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/controlplaneio-fluxcd/flux-operator/releases/download/v0.28.0/flux-operator_0.28.0_linux_amd64.tar.gz"
        sha256 "9c4cfd4cbe8650dac2fdd5f6a450d7f95f0e7be04674b980c2c63bf7bab0aefa"

        def install
          bin.install "flux-operator"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/controlplaneio-fluxcd/flux-operator/releases/download/v0.28.0/flux-operator_0.28.0_linux_arm64.tar.gz"
        sha256 "2774b52da2995d720f9a95e3ba2d71fc69917cf9e008c1d64a6c694c86574e3e"

        def install
          bin.install "flux-operator"
        end
      end
    end
  end

  test do
    system "#{bin}/flux-operator--version"
  end
end
