# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FluxOperator < Formula
  desc "Flux Operator CLI"
  homepage "https://fluxcd.control-plane.io/operator/cli"
  version "LATEST_RELEASE"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/controlplaneio-fluxcd/flux-operator/releases/download/vLATEST_RELEASE/flux-operator_LATEST_RELEASE_darwin_amd64.tar.gz"
      sha256 "FLUX_OPERATOR_DARWIN_AMD64"

      def install
        bin.install "flux-operator"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/controlplaneio-fluxcd/flux-operator/releases/download/vLATEST_RELEASE/flux-operator_LATEST_RELEASE_darwin_arm64.tar.gz"
      sha256 "FLUX_OPERATOR_DARWIN_ARM64"

      def install
        bin.install "flux-operator"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/controlplaneio-fluxcd/flux-operator/releases/download/vLATEST_RELEASE/flux-operator_LATEST_RELEASE_linux_amd64.tar.gz"
        sha256 "FLUX_OPERATOR_LINUX_AMD64"

        def install
          bin.install "flux-operator"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/controlplaneio-fluxcd/flux-operator/releases/download/vLATEST_RELEASE/flux-operator_LATEST_RELEASE_linux_arm64.tar.gz"
        sha256 "FLUX_OPERATOR_LINUX_ARM64"

        def install
          bin.install "flux-operator"
        end
      end
    end
  end

  test do
    system "#{bin}/flux-operator--version"
  end
end
